apiVersion: v2
name: sd-card-capture
description: "BIAN Service Domain: Card Capture (Process pattern, Operations and Execution)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - process
annotations:
  bian/business-area: "Operations and Execution"
  bian/business-domain: "Cards"
  bian/asset-type: "Captured Card"
  bian/control-record: "Captured Card Procedure"
